[package]
name = "draw"
version = "0.1.0"
edition = "2021"
links = "X11"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
stb = "0.3.2"
x11 = "2.21.0"

[rust]
debug = true
debuginfo-level = 1


[profile.release]
debug = 1

#[target.<triple>.<links>] # `links` build script override
#rustc-link-lib = ["X11"]
